- src/RPC.js
Added RPC method for client wallet.
> add get-tx-block-height method to rpc + getMinedTransaction error msg

- src/Transaction.js
Needed to determine expiration epoch for data explorer display on MadNet Wallet
> expose transaction utils to class constructor

- package-lock.json
- src/Account.js
- src/Constants.js
- src/RPC.js
- src/Transaction/Utils.js
- src/Validator.js
- src/Wallet.js
Added
- pagination token to getValueUTXOIDs rpc method
- back of retry logic to all rpc methods
- validation hexToInt
Removed
- whitespaces / lint
> Add PaginationToken to RPC method

- src/RPC.js
Adding the get pending transaction method to rpc module.
> getPendingTransaction rpc method

- src/RPC.js
added backOffRetry to the promise catch on the network request function
> RPC back off retry logic addition

- src/Account.js
Remove account from the accounts array
> remove account

- src/RPC.js
- src/Transaction.js
- Fix error handling in sendTransaction
- Check DS index in spending utxos
> Minor patch

- src/Transaction.js
- src/Transaction/Tx.js
- src/Transaction/Utils.js
Include rewards when calculating the fee + when there is reward, use spendUTXO to create the valuestore with fees on the Vout
> update for fees on datastore rewards

- src/Transaction.js
- src/Transaction/Tx.js
- Additionally has estimateFee patch, to provide deposit costs regardless of if a DataStore is consumed
> Add estimate fee error hoist optional parameter

- src/RPC.js
- src/Transaction.js
> JS Doc Fixes

- dotenv
Cleans up dotenv to reflect the current required environment for testing, etc
> Cleanup dotenv to reflect current environment requirements

- src/Util/Generic.js
- src/Util/Tx.js
- src/Util/index.js
Cleanup utilities and add generic util set
> Cleanup utils

- debugging-scripts/runtimeListener.js
- debugging-scripts/test.js
More for debugging when things arise, includes two quick checks of ValueStore and DataStore TXs
Additionally provides an event listener for grabbing values out of runtime context by providing an event pub/sub model.
> Add debugging script outline and runtime helper

- src/Account.js
- src/RPC.js
- src/Transaction.js
- src/Wallet.js
Cleanup JSDoc on account,wallet, and RPC.
Additionally had QoL fix to RPC to poll for chainID if an RPC endpoint is provided.
> Docclean account wallet qol rpc

- src/Account.js
- src/RPC.js
- src/Transaction/Tx.js
- tests/integration/rpc.js
- tests/integration/transaction.js
- tests/integration/txTransaction.js
- tests/unit/multiSig.js
- tests/unit/txUtil.js
https://madhive.atlassian.net/browse/MP-807
> MP-807 Remove atomic swap

- src/Account.js
https://madhive.atlassian.net/browse/MP-709
> MP-709 Redo getAccountIndex

- src/Account.js
https://madhive.atlassian.net/browse/MP-708
> MP-708 Rework getAccount

- src/Account.js
https://madhive.atlassian.net/browse/MP-707
> MP-707 Redo addAccount

- src/Signers/MultiSig.js
- tests/unit/multiSig.js
https://madhive.atlassian.net/browse/MP-791
> MP-791 Remove multisign that is not a bnsigner

- src/Util/Eth.js
- src/Util/Hash.js
- src/Util/Tx.js
- src/Util/Validator.js
- src/Util/VerifySignature.js
- src/Wallet.js
https://madhive.atlassian.net/browse/MP-713
> MP-713 Rework utility folder

- coverage/cobertura-coverage.xml
- package-lock.json
- src/Util/Faucet.js
- src/Util/index.js
- tests/unit/faucetUtil.js
https://madhive.atlassian.net/browse/MP-311
> Add Faucet URL Parameter
